/* Shared content for GFC site. */

export const GFC_DATA = {
  projects: [
    {
      id: "fashion-discovery-stage",
      number: "01",
      name: "Global Fashion Code",
      subtitle: "Your live access to the global fashion industry.",
      tagline: "A flagship platform — new faces, new designers, new direction.",
      forWho: "Models · Designers · Stylists · Agencies",
      location: "Batumi · Tbilisi · Istanbul",
      year: "2024 — present",
      hero: "/cards/01.jpg",
      receive: [
        { n: "01", t: "International castings", d: "Direct presentation to scouting agents from Paris, Milan, Tokyo, Seoul and New York." },
        { n: "02", t: "Industry placement", d: "Selected participants signed to partner agencies on the closing night." },
        { n: "03", t: "Editorial coverage", d: "Full editorial photo and video portfolio shot during the show week." },
        { n: "04", t: "Workshops", d: "Three days of intensive training with international tutors and creative directors." },
      ],
    },
    {
      id: "future-idols",
      number: "02",
      name: "Future Idol Showcase",
      subtitle: "The runway for the next generation of models.",
      tagline: "Talent under twenty-five — print, runway, campaign, screen.",
      forWho: "Models 16–25 · Performers · Faces",
      location: "International tour",
      year: "2025 season",
      hero: "/cards/02.jpg",
      receive: [
        { n: "01", t: "Open castings", d: "Live castings in eight cities across Europe and the Caucasus." },
        { n: "02", t: "Mentorship", d: "Six-week mentorship by working directors and casting agents." },
        { n: "03", t: "Portfolio", d: "Studio test, video reel and runway tape — produced in-house." },
        { n: "04", t: "Career placement", d: "Top fifteen presented to industry decision-makers at season finale." },
      ],
    },
    {
      id: "global-fashion-showcase",
      number: "03",
      name: "Leaders Intensive",
      subtitle: "For agency leaders ready to build, not compete.",
      tagline: "A bi-annual showcase pairing established houses with emerging studios.",
      forWho: "Designers · Houses · Press · Buyers",
      location: "Annual — rotating capitals",
      year: "Since 2022",
      hero: "/cards/03.jpg",
      receive: [
        { n: "01", t: "Runway slot", d: "Curated runway slot at the showcase main stage with full production." },
        { n: "02", t: "Press exposure", d: "International press list — print, digital, broadcast." },
        { n: "03", t: "Trade buyer access", d: "Pre-showcase trade room with vetted boutique and department buyers." },
      ],
    },
    {
      id: "beauty-idols",
      number: "04",
      name: "Fashion Discovery Stage",
      subtitle: "The first step into professional modeling.",
      tagline: "For the artists, faces and brands defining contemporary beauty.",
      forWho: "Makeup Artists · Faces · Beauty Editors",
      location: "Tbilisi · Paris",
      year: "Annual",
      hero: "/cards/04.jpg",
      receive: [
        { n: "01", t: "Editorial shoot", d: "Two-day editorial shoot with rotating creative directors and stylists." },
        { n: "02", t: "Conference", d: "Talks and panels with senior beauty editors and house representatives." },
        { n: "03", t: "Pro contacts", d: "Direct introductions to beauty desks at international magazines." },
      ],
    },
    {
      id: "leaders-intensive",
      number: "05",
      name: "Global Beauty Code Award",
      subtitle: "Where beauty creatives become visible.",
      tagline: "Brand, business and creative direction — taught by people who run it.",
      forWho: "Founders · Directors · Senior creatives",
      location: "Closed cohort",
      year: "Twice yearly",
      hero: "/cards/05.jpg",
      receive: [
        { n: "01", t: "Eight-week cohort", d: "Closed cohort of twenty-five, eight intensive weeks." },
        { n: "02", t: "Founder sessions", d: "Working sessions with founders of agencies, houses and platforms." },
        { n: "03", t: "Business clinic", d: "One-on-one operational and creative clinics with industry advisers." },
      ],
    },
  ],

  event: {
    title: "Fashion Discovery Stage",
    place: "Batumi · Georgia",
    date: "7 — 9 May 2026",
    poster: "/images/event/event-poster.webp",
    categories: [
      { n: "01", l: "Runway Shows" },
      { n: "02", l: "International Castings" },
      { n: "03", l: "Fashion Conference" },
      { n: "04", l: "Workshops" },
      { n: "05", l: "Awards" },
    ],
  },

  partners: [
    { title: "Agencies", n: "01", names: ["MAJOR ATELIER", "VIVIENNE / KIM", "FORM BUREAU", "STUDIO NORTH", "MAISON ARRO", "OST AGENCY"] },
    { title: "Media",    n: "02", names: ["MODE", "L'OBSERVÉ", "ORBIT", "CONTRA", "FROM PARIS", "QUARTERLY"] },
    { title: "Beauty Partners", n: "03", names: ["ÉCLAT", "MAISON 7", "BÉL—", "ROUGE EDIT", "NU LAB", "GRAY HOUSE"] },
    { title: "Sponsors", n: "04", names: ["MŪN", "ALTITUDE", "ZONE 5", "PALAIS GROUP", "AMARO", "BLANCO"] },
  ],

  roles: [
    { id: "model",        label: "Model" },
    { id: "agency",       label: "Agency" },
    { id: "designer",     label: "Designer" },
    { id: "photographer", label: "Photographer" },
    { id: "makeup",       label: "Makeup Artist" },
    { id: "stylist",      label: "Stylist" },
    { id: "sponsor",      label: "Sponsor / Partner" },
    { id: "media",        label: "Media" },
  ],
};
