/* Shared content for GFC site. */

export const GFC_DATA = {
  projects: [
    {
      id: "fashion-discovery-stage",
      number: "01",
      name: "Global Fashion Code",
      subtitle: "Your live access to the global fashion industry.",
      tagline: "Your live access to the global fashion industry.",
      forWho: "Models · Designers · Stylists · Agencies",
      location: "Batumi · Tbilisi · Istanbul",
      year: "2024 — present",
      hero: "/cards/01.jpg",
      description: "A 3-day curated fashion project where selected models, beauty talents, brands and industry leaders meet face-to-face with scouts, bookers and top model agencies from Europe and Asia.",
      categories: [
        "Education", "Castings", "Agency Meetings", "Runway Shows",
        "Photoshoots", "Awards", "Media Visibility", "Contract Opportunities",
      ],
      selectionNote: "Participation is by selection only.",
      days: [
        { n: "Day 1", t: "Global Fashion Education" },
        { n: "Day 2", t: "Global Fashion Casting" },
        { n: "Day 3", t: "Global Fashion Show & Award" },
      ],
      audience: "For Models · Kids & Adults · Designers · Photographers · Makeup Artists · Hair Stylists · Stylists · Model Agencies · Fashion Leaders",
      receive: [
        { n: "01", t: "International castings", d: "Direct presentation to scouting agents from Paris, Milan, Tokyo, Seoul and New York." },
        { n: "02", t: "Industry placement", d: "Selected participants signed to partner agencies on the closing night." },
        { n: "03", t: "Editorial coverage", d: "Full editorial photo and video portfolio shot during the show week." },
        { n: "04", t: "Workshops", d: "Three days of intensive training with international tutors and creative directors." },
      ],
    },
    {
      id: "future-idols",
      number: "02",
      name: "Future Idol Showcase",
      subtitle: "The runway for the next generation of models.",
      tagline: "The runway for the next generation of models.",
      forWho: "Models 16–25 · Performers · Faces",
      location: "International tour",
      year: "2025 season",
      hero: "/cards/02.jpg",
      description: [
        "A special showcase for the most promising models aged 14–22, with a height of 170–180 cm, created for talents who have the potential to sign with international model agencies in Europe, Asia and the USA.",
        "This is not just a show. It is a professional presentation of selected models in front of the industry, created to open real opportunities for international representation, contracts and career growth.",
      ],
      selectionNote: "Participation is by selection only.",
      receive: [
        { n: "01", t: "Open castings", d: "Live castings in eight cities across Europe and the Caucasus." },
        { n: "02", t: "Mentorship", d: "Six-week mentorship by working directors and casting agents." },
        { n: "03", t: "Portfolio", d: "Studio test, video reel and runway tape — produced in-house." },
        { n: "04", t: "Career placement", d: "Top fifteen presented to industry decision-makers at season finale." },
      ],
    },
    {
      id: "global-fashion-showcase",
      number: "03",
      name: "Leaders Intensive",
      subtitle: "For agency leaders ready to build, not compete.",
      tagline: "For agency leaders ready to build, not compete.",
      forWho: "Designers · Houses · Press · Buyers",
      location: "Annual — rotating capitals",
      year: "Since 2022",
      hero: "/cards/03.jpg",
      description: [
        "A strategic meeting for model agency directors who are ready to connect, collaborate and create a stronger professional community within the modeling industry.",
        "The intensive is led by Anastasia Soldatova, founder of MAG Model Agent Group, listed on Models.com, and producer of Global Fashion Code.",
        "This format is created for leaders who want to grow internationally, exchange experience, build partnerships and see the modeling business from a stronger strategic perspective.",
      ],
      receive: [
        { n: "01", t: "Runway slot", d: "Curated runway slot at the showcase main stage with full production." },
        { n: "02", t: "Press exposure", d: "International press list — print, digital, broadcast." },
        { n: "03", t: "Trade buyer access", d: "Pre-showcase trade room with vetted boutique and department buyers." },
      ],
    },
    {
      id: "beauty-idols",
      number: "04",
      name: "Fashion Discovery Stage",
      subtitle: "The first step into professional modeling.",
      tagline: "The first step into professional modeling.",
      forWho: "Makeup Artists · Faces · Beauty Editors",
      location: "Tbilisi · Paris",
      year: "Annual",
      hero: "/cards/04.jpg",
      description: [
        "Once a year in Georgia, we create an open model event for talents who want to learn, grow and understand what the international modeling industry really requires.",
        "Unlike Global Fashion Code, this format is open to all models who want to participate, without preliminary casting.",
        "Fashion Discovery Stage is focused on education, preparation, runway practice and professional growth. It is created for models who want to move from interest to real industry understanding.",
      ],
      receive: [
        { n: "01", t: "Editorial shoot", d: "Two-day editorial shoot with rotating creative directors and stylists." },
        { n: "02", t: "Conference", d: "Talks and panels with senior beauty editors and house representatives." },
        { n: "03", t: "Pro contacts", d: "Direct introductions to beauty desks at international magazines." },
      ],
    },
    {
      id: "leaders-intensive",
      number: "05",
      name: "Global Beauty Code Award",
      subtitle: "Where beauty creatives become visible.",
      tagline: "Where beauty creatives become visible.",
      forWho: "Founders · Directors · Senior creatives",
      location: "Closed cohort",
      year: "Twice yearly",
      hero: "/cards/05.jpg",
      description: [
        "An international award project for makeup artists, hairstylists and beauty professionals who want to be seen, recognized and remembered inside the fashion & beauty industry.",
        "Participants have the opportunity to become award nominees or winners, enter the history of the Global Fashion Code project and receive magazine publication with a personal interview.",
        "This is a platform for beauty creatives who do not want to stay behind the scenes, but want their work, vision and professional identity to be noticed.",
      ],
      receive: [
        { n: "01", t: "Eight-week cohort", d: "Closed cohort of twenty-five, eight intensive weeks." },
        { n: "02", t: "Founder sessions", d: "Working sessions with founders of agencies, houses and platforms." },
        { n: "03", t: "Business clinic", d: "One-on-one operational and creative clinics with industry advisers." },
      ],
    },
  ],

  event: {
    title: "Fashion Discovery Stage",
    place: "Batumi · Georgia",
    date: "7 — 9 May 2026",
    poster: "/images/event/event-poster.webp",
    categories: [
      { n: "01", l: "Runway Shows" },
      { n: "02", l: "International Castings" },
      { n: "03", l: "Fashion Conference" },
      { n: "04", l: "Workshops" },
      { n: "05", l: "Awards" },
    ],
  },

  partners: [
    { title: "Agencies", n: "01", names: ["MAJOR ATELIER", "VIVIENNE / KIM", "FORM BUREAU", "STUDIO NORTH", "MAISON ARRO", "OST AGENCY"] },
    { title: "Media",    n: "02", names: ["MODE", "L'OBSERVÉ", "ORBIT", "CONTRA", "FROM PARIS", "QUARTERLY"] },
    { title: "Beauty Partners", n: "03", names: ["ÉCLAT", "MAISON 7", "BÉL—", "ROUGE EDIT", "NU LAB", "GRAY HOUSE"] },
    { title: "Sponsors", n: "04", names: ["MŪN", "ALTITUDE", "ZONE 5", "PALAIS GROUP", "AMARO", "BLANCO"] },
  ],

  roles: [
    { id: "model",        label: "Model" },
    { id: "agency",       label: "Agency" },
    { id: "designer",     label: "Designer" },
    { id: "photographer", label: "Photographer" },
    { id: "makeup",       label: "Makeup Artist" },
    { id: "stylist",      label: "Stylist" },
    { id: "sponsor",      label: "Sponsor / Partner" },
    { id: "media",        label: "Media" },
  ],
};
