export const legalContent = {
  en: {
    pageLabel: '( Legal )',
    pageTitle: 'Legal &\nPrivacy',
    pageMeta: 'Global Fashion Code / MAG Model Agent Group · Austria, Kufstein 6330, Einfangstrasse 6 · info@globalfashioncode.com',
    sections: [
      {
        id: 'privacy',
        nav: 'Privacy Policy',
        title: '1. Privacy Policy',
        lastUpdated: 'Last updated: 15.06.2026',
        blocks: [
          { type: 'p', text: 'Global Fashion Code respects your privacy and is committed to protecting your personal data. This Privacy Policy explains how we collect, use, store, share and protect personal data when you visit our website, submit an application, contact us or participate in Global Fashion Code projects, events, castings, education programs, showcases, awards, photoshoots, media activities or related professional opportunities.' },
          { type: 'p', text: 'We process personal data in accordance with applicable data protection laws, including the General Data Protection Regulation (GDPR) and applicable Austrian data protection rules.' },
          { type: 'h3', text: '1.1 Data Controller' },
          { type: 'p', text: 'The data controller responsible for the processing of your personal data is MAG Model Agent Group, operating project Global Fashion Code.' },
          { type: 'meta', label: 'Address', value: 'Austria, Kufstein 6330, Einfangstrasse 6' },
          { type: 'meta', label: 'Email', value: 'info@globalfashioncode.com' },
          { type: 'meta', label: 'Website', value: 'www.globalfashioncode.com' },
          { type: 'h3', text: '1.2 Personal Data We May Collect' },
          { type: 'p', text: 'We may collect and process the following personal data: name, surname, date of birth, age, gender, nationality, country of residence, contact details, email address, phone number, social media profiles and communication details; professional information including portfolio, photos, videos, measurements, height, clothing size, shoe size, modelling experience, agency representation, creative work, brand information, professional background and links to previous work; application data submitted through website forms, email, social media, partner platforms or direct communication; parent or legal guardian details where the applicant or participant is under 18; event-related data including participation status, casting results, schedules, attendance, backstage content, photos, videos, interviews, media materials, award results and professional feedback; payment, invoice and transaction data where participation fees, services or purchases are involved; technical data including IP address, browser type, device information, website usage data, cookie preferences and analytics data where permitted.' },
          { type: 'h3', text: '1.3 Purposes of Processing' },
          { type: 'p', text: 'We process personal data to receive, review and manage applications for Global Fashion Code projects; to select participants for castings, showcases, education programs, runway shows, awards, photoshoots and agency meetings; to communicate with applicants, participants, parents, legal guardians, agencies, partners, media, sponsors and industry professionals; to organise and manage events, schedules, castings, rehearsals, fittings, photoshoots, education sessions, backstage activities, awards and professional meetings; to present selected talents, brands and professionals to international model agencies, scouts, bookers, casting directors, designers, photographers, media partners, sponsors and other professional partners; to create, publish and archive project-related photo, video, editorial, social media, press and promotional materials where permitted by law or separate consent; to process payments, invoices, contracts and administrative matters; to improve our website, communication, services, application process and event experience; to comply with legal, accounting, tax, security and regulatory obligations.' },
          { type: 'h3', text: '1.4 Legal Basis for Processing' },
          { type: 'p', text: 'Consent: when you submit an application, agree to receive communications, agree to cookie categories or provide media permission where required.' },
          { type: 'p', text: 'Pre-contractual or contractual necessity: when processing is necessary to review your application, organise participation or provide agreed services.' },
          { type: 'p', text: 'Legitimate interests: when processing is necessary for project management, communication with partners, event organisation, business protection, website improvement, professional presentation and promotion of Global Fashion Code, provided that your rights and freedoms do not override these interests.' },
          { type: 'p', text: 'Legal obligations: when processing is required for accounting, tax, safety, legal or regulatory reasons.' },
          { type: 'h3', text: '1.5 Participants Under 18' },
          { type: 'p', text: 'Some Global Fashion Code projects may involve minors. If an applicant or participant is under 18, we may require the involvement, consent and contact details of a parent or legal guardian. We do not knowingly accept participation of minors without appropriate parental or legal guardian involvement where required.' },
          { type: 'h3', text: '1.6 Sharing Personal Data' },
          { type: 'p', text: 'We may share personal data where necessary with trusted third parties, including: international model agencies, scouts, bookers, casting directors and fashion industry professionals; designers, photographers, videographers, makeup artists, hairstylists, stylists, production teams, venues, sponsors and event partners; media partners, magazines, PR partners, social media teams and publishing partners; IT providers, website hosting providers, email systems, cloud storage providers, form tools, CRM tools, analytics tools and payment providers; accountants, legal advisors, insurance providers, administrative service providers and public authorities where required by law. We do not sell personal data.' },
          { type: 'h3', text: '1.7 International Data Transfers' },
          { type: 'p', text: 'Global Fashion Code works with international agencies, scouts, bookers, media and professional partners. This means that personal data and selected application or project materials may be transferred or made accessible outside your country of residence, including within the European Economic Area and, where relevant, to countries outside the EEA. Where required, we take appropriate steps to protect personal data in accordance with applicable law.' },
          { type: 'h3', text: '1.8 Photos, Videos and Media Materials' },
          { type: 'p', text: 'Global Fashion Code projects may be photographed, filmed and covered by media teams. Photos, videos, interviews and other project-related materials may be used for website content, social media, press, portfolio, event documentation, promotional materials, editorial publications, archive and partner communication. Where required, media usage will be covered by a separate Media Release / Participation Terms Agreement.' },
          { type: 'h3', text: '1.9 Cookies and Analytics' },
          { type: 'p', text: 'Our website may use cookies and similar technologies. Strictly necessary cookies are used to make the website function and cannot be switched off. Optional cookies, including analytics, marketing, tracking and social media cookies, are used only where permitted by law and, where required, only with your prior consent. You can accept all cookies, reject non-essential cookies or manage your preferences through the cookie banner.' },
          { type: 'h3', text: '1.10 Data Retention' },
          { type: 'p', text: 'We keep personal data only for as long as necessary for the purposes described in this Privacy Policy. Application data may be kept for a reasonable period to manage selections, future opportunities and communication with applicants, unless deletion is requested earlier. Photos, videos, press materials, published content and project archives may remain available where they have been lawfully created and used for event, editorial, archive, documentation, portfolio or promotional purposes.' },
          { type: 'h3', text: '1.11 Your Rights' },
          { type: 'p', text: 'Depending on applicable law, you may have the right to: request access to your personal data; request correction of inaccurate or incomplete data; request deletion of your personal data; request restriction of processing; object to certain types of processing; withdraw consent at any time where processing is based on consent; request data portability where applicable; lodge a complaint with a competent data protection authority. To exercise your rights, please contact: info@globalfashioncode.com.' },
          { type: 'h3', text: '1.12 Security' },
          { type: 'p', text: 'We take reasonable technical and organisational measures to protect personal data against unauthorised access, loss, misuse, alteration or disclosure.' },
          { type: 'h3', text: '1.13 Changes to This Privacy Policy' },
          { type: 'p', text: 'We may update this Privacy Policy from time to time. The updated version will be published on this page with a new "Last updated" date.' },
          { type: 'h3', text: '1.14 Contact' },
          { type: 'p', text: 'For questions about this Privacy Policy or personal data processing, please contact Global Fashion Code / MAG Model Agent Group at info@globalfashioncode.com.' },
        ],
      },
      {
        id: 'cookies',
        nav: 'Cookie Policy',
        title: '2. Cookie Policy',
        lastUpdated: 'Last updated: 15.06.2026',
        blocks: [
          { type: 'p', text: 'This Cookie Policy explains how Global Fashion Code uses cookies and similar technologies on our website. Cookies are small text files stored on your device when you visit a website. They help websites function, remember preferences, understand website usage and support communication or marketing activities.' },
          { type: 'h3', text: '2.1 Types of Cookies We Use' },
          { type: 'p', text: 'Strictly Necessary Cookies — Required for the website to function, remain secure and provide basic features. These cookies cannot be switched off because the website cannot work properly without them.' },
          { type: 'p', text: 'Analytics Cookies — Help us understand how visitors use our website, which pages are visited and how we can improve our content, structure and user experience. Used only with your consent where required.' },
          { type: 'p', text: 'Marketing and Social Media Cookies — May be used to measure campaigns, personalise content, connect with social media platforms, support advertising activities or understand the effectiveness of communication. Used only with your consent where required.' },
          { type: 'p', text: 'Preference Cookies — May remember your selected settings, such as language or cookie preferences, where applicable.' },
          { type: 'h3', text: '2.2 Consent' },
          { type: 'p', text: 'When you visit our website, you may accept all cookies, reject non-essential cookies or manage your preferences by category. Strictly necessary cookies are always active because they are required for the website to operate. Optional cookies, including analytics, marketing, tracking and social media cookies, are used only if you give consent where required by law. You may change or withdraw your consent at any time through the Cookie Settings link on the website.' },
          { type: 'h3', text: '2.3 Third-Party Cookies' },
          { type: 'p', text: 'Some cookies may be placed by third-party providers, such as analytics tools, social media platforms, embedded content providers, advertising tools or payment systems. These third parties may process data according to their own privacy and cookie policies.' },
        ],
      },
      {
        id: 'terms',
        nav: 'Terms & Conditions',
        title: '3. Terms & Conditions',
        lastUpdated: 'Last updated: 15.06.2026',
        blocks: [
          { type: 'p', text: 'These Website Terms & Conditions govern the use of the Global Fashion Code website and online content. By using this website, you agree to these Terms & Conditions.' },
          { type: 'h3', text: '3.1 Website Operator' },
          { type: 'meta', label: 'Project', value: 'Global Fashion Code' },
          { type: 'meta', label: 'Address', value: 'Austria, Kufstein 6330, Einfangstrasse 6' },
          { type: 'meta', label: 'Email', value: 'info@globalfashioncode.com' },
          { type: 'h3', text: '3.2 Purpose of the Website' },
          { type: 'p', text: 'The website provides information about Global Fashion Code projects, including fashion events, castings, education programs, showcases, awards, application opportunities, media activities and professional networking formats. The information on the website is provided for general informational and promotional purposes.' },
          { type: 'h3', text: '3.3 Applications and Selection' },
          { type: 'p', text: 'Submitting an application through the website does not guarantee acceptance, participation, casting approval, agency representation, contract, award, publication, paid work or any specific professional result. Global Fashion Code may review applications based on project criteria, professional suitability, availability, age, height, measurements, portfolio, experience, project needs and partner requirements.' },
          { type: 'h3', text: '3.4 No Guarantee of Contracts or Results' },
          { type: 'p', text: 'Global Fashion Code creates opportunities for visibility, education, casting access, professional presentation, agency meetings, networking and media exposure. However, final decisions regarding contracts, bookings, representation, publications, awards, cooperation or future opportunities are made by independent agencies, partners, clients, media, sponsors, judges or industry professionals. No statement on the website should be interpreted as a guarantee of contract, agency signing, paid work, visa, publication, award, booking or financial result.' },
          { type: 'h3', text: '3.5 Intellectual Property' },
          { type: 'p', text: 'All website content, including names, logos, project titles, texts, images, videos, graphics, layouts, design, concepts, program structures and materials, belongs to Global Fashion Code or its licensors unless otherwise stated. You may not copy, reproduce, distribute, modify, sell, publish or use website content for commercial purposes without prior written permission.' },
          { type: 'h3', text: '3.6 User Conduct' },
          { type: 'p', text: 'You agree not to misuse the website, submit false information, upload unlawful content, infringe third-party rights, attempt to access restricted systems, damage the website, use automated scraping tools or engage in conduct that may harm Global Fashion Code, its partners, participants or users.' },
          { type: 'h3', text: '3.7 Limitation of Liability' },
          { type: 'p', text: 'To the extent permitted by applicable law, Global Fashion Code is not liable for indirect losses, missed opportunities, rejected applications, technical problems, website interruptions, third-party actions, travel issues, agency decisions, casting results or reliance on website information.' },
          { type: 'h3', text: '3.8 Governing Law' },
          { type: 'p', text: 'These Terms & Conditions are governed by the laws of Austria, unless mandatory consumer protection or other applicable laws provide otherwise. Any disputes shall first be discussed in good faith. If no amicable solution is found, competent courts shall be determined in accordance with applicable law.' },
        ],
      },
      {
        id: 'imprint',
        nav: 'Legal Notice',
        title: '4. Legal Notice / Imprint',
        blocks: [
          { type: 'p', text: 'Information according to applicable Austrian legal requirements, including the Austrian E-Commerce Act and Media Act, where applicable.' },
          { type: 'h3', text: 'Website Operator / Media Owner' },
          { type: 'meta', label: 'Website', value: 'www.globalfashioncode.com' },
          { type: 'meta', label: 'Business Name', value: 'Global Fashion Code' },
          { type: 'meta', label: 'Operating Entity', value: 'MAG Model Agent Group' },
          { type: 'meta', label: 'Address', value: 'Einfangstrasse 6, Kufstein 6330, Austria' },
          { type: 'meta', label: 'Email', value: 'info@globalfashioncode.com' },
          { type: 'h3', text: 'Business Purpose' },
          { type: 'p', text: 'Fashion events, model castings, education programs, fashion showcases, media projects, professional networking and related services.' },
          { type: 'h3', text: 'Disclaimer' },
          { type: 'p', text: 'We make reasonable efforts to keep the information on this website accurate and up to date. However, we do not guarantee that all information is complete, current or error-free.' },
          { type: 'h3', text: 'External Links' },
          { type: 'p', text: 'This website may contain links to external websites. We are not responsible for the content, privacy practices or security of external websites.' },
          { type: 'h3', text: 'Copyright' },
          { type: 'p', text: 'All content on this website, including texts, images, videos, logos and design elements, is protected by copyright and may not be used without prior written permission.' },
        ],
      },
    ],
  },

  ru: {
    pageLabel: '( Правовая информация )',
    pageTitle: 'Правовая\nинформация',
    pageMeta: 'Global Fashion Code / MAG Model Agent Group · Австрия, Куфштайн 6330, Einfangstrasse 6 · info@globalfashioncode.com',
    sections: [
      {
        id: 'privacy',
        nav: 'Политика конфиденциальности',
        title: '1. Политика конфиденциальности',
        lastUpdated: 'Последнее обновление: 15.06.2026',
        blocks: [
          { type: 'p', text: 'Global Fashion Code уважает вашу конфиденциальность и обязуется защищать ваши персональные данные. Настоящая Политика конфиденциальности объясняет, как мы собираем, используем, храним, передаём и защищаем персональные данные при посещении нашего сайта, подаче заявки, обращении к нам или участии в проектах, мероприятиях, кастингах, образовательных программах, показах, конкурсах, фотосессиях, медиапроектах и смежных профессиональных возможностях Global Fashion Code.' },
          { type: 'p', text: 'Мы обрабатываем персональные данные в соответствии с применимым законодательством о защите данных, включая Общий регламент по защите данных (GDPR) и австрийские нормы защиты данных.' },
          { type: 'h3', text: '1.1 Контролёр данных' },
          { type: 'p', text: 'Контролёром, ответственным за обработку ваших персональных данных, является MAG Model Agent Group, управляющая проектом Global Fashion Code.' },
          { type: 'meta', label: 'Адрес', value: 'Австрия, Куфштайн 6330, Einfangstrasse 6' },
          { type: 'meta', label: 'Email', value: 'info@globalfashioncode.com' },
          { type: 'meta', label: 'Сайт', value: 'www.globalfashioncode.com' },
          { type: 'h3', text: '1.2 Персональные данные, которые мы можем собирать' },
          { type: 'p', text: 'Мы можем собирать и обрабатывать следующие персональные данные: имя, фамилия, дата рождения, возраст, пол, гражданство, страна проживания, контактные данные, адрес электронной почты, номер телефона, профили в социальных сетях и данные для связи; профессиональная информация, включая портфолио, фотографии, видео, параметры, рост, размер одежды, размер обуви, опыт в модельном бизнесе, представительство агентством, творческие работы, информацию о бренде, профессиональный опыт и ссылки на предыдущие работы; данные заявки, поданной через форму на сайте, по электронной почте, через социальные сети, партнёрские платформы или напрямую; данные родителя или законного представителя, если участник младше 18 лет; данные, связанные с мероприятием, включая статус участия, результаты кастинга, расписание, посещаемость, закулисный контент, фотографии, видео, интервью, медиаматериалы, результаты конкурса и профессиональную обратную связь; платёжные, счётные и транзакционные данные при наличии участия, услуг или покупок; технические данные, включая IP-адрес, тип браузера, информацию об устройстве, данные об использовании сайта, настройки cookie и аналитические данные там, где это разрешено.' },
          { type: 'h3', text: '1.3 Цели обработки' },
          { type: 'p', text: 'Мы обрабатываем персональные данные для получения, рассмотрения и управления заявками на участие в проектах Global Fashion Code; для отбора участников на кастинги, показы, образовательные программы, подиумные шоу, конкурсы, фотосессии и встречи с агентствами; для связи с заявителями, участниками, родителями, законными представителями, агентствами, партнёрами, СМИ, спонсорами и профессионалами отрасли; для организации и проведения мероприятий, кастингов, репетиций, примерок, фотосессий, образовательных сессий, закулисной деятельности, конкурсов и деловых встреч; для представления отобранных талантов, брендов и профессионалов международным модельным агентствам, скаутам, букерам, кастинг-директорам, дизайнерам, фотографам, медиапартнёрам, спонсорам и другим профессиональным партнёрам; для создания, публикации и архивирования проектных фото, видео, редакционных, социальных, пресс- и рекламных материалов там, где это разрешено законом или отдельным согласием; для обработки платежей, счетов, договоров и административных вопросов; для улучшения сайта, коммуникаций, сервисов, процесса подачи заявок и опыта участия в мероприятиях; для соблюдения юридических, бухгалтерских, налоговых, охранных и нормативных обязательств.' },
          { type: 'h3', text: '1.4 Правовые основания для обработки' },
          { type: 'p', text: 'Согласие: при подаче заявки, согласии на получение коммуникаций, согласии на категории cookie или предоставлении разрешения на медиаиспользование там, где это требуется.' },
          { type: 'p', text: 'Преддоговорная или договорная необходимость: когда обработка необходима для рассмотрения заявки, организации участия или предоставления согласованных услуг.' },
          { type: 'p', text: 'Законные интересы: когда обработка необходима для управления проектами, коммуникации с партнёрами, организации мероприятий, защиты бизнеса, улучшения сайта, профессионального представления и продвижения Global Fashion Code при условии, что ваши права и свободы не превалируют над этими интересами.' },
          { type: 'p', text: 'Юридические обязательства: когда обработка требуется по бухгалтерским, налоговым, правовым или нормативным основаниям.' },
          { type: 'h3', text: '1.5 Участники младше 18 лет' },
          { type: 'p', text: 'Некоторые проекты Global Fashion Code могут предполагать участие несовершеннолетних. Если заявитель или участник младше 18 лет, мы можем потребовать участия, согласия и контактных данных родителя или законного представителя. Мы не принимаем участие несовершеннолетних без надлежащего участия родителя или законного представителя там, где это требуется.' },
          { type: 'h3', text: '1.6 Передача персональных данных' },
          { type: 'p', text: 'Мы можем передавать персональные данные при необходимости надёжным третьим сторонам, включая: международные модельные агентства, скаутов, букеров, кастинг-директоров и профессионалов модной индустрии; дизайнеров, фотографов, видеографов, визажистов, парикмахеров, стилистов, производственные группы, площадки, спонсоров и партнёров мероприятий; медиапартнёров, журналы, PR-партнёров, команды социальных сетей и издательских партнёров; IT-провайдеров, провайдеров хостинга, почтовые системы, провайдеров облачного хранения, инструменты форм, CRM, аналитические инструменты и платёжные провайдеры; бухгалтеров, юридических консультантов, страховых провайдеров, поставщиков административных услуг и органы государственной власти в соответствии с законодательством. Мы не продаём персональные данные.' },
          { type: 'h3', text: '1.7 Международная передача данных' },
          { type: 'p', text: 'Global Fashion Code работает с международными агентствами, скаутами, букерами, медиа и профессиональными партнёрами. Это означает, что персональные данные и отдельные материалы заявок или проектов могут передаваться или быть доступны за пределами вашей страны проживания, в том числе в рамках Европейской экономической зоны и, при необходимости, в страны за её пределами. При необходимости мы принимаем надлежащие меры по защите персональных данных в соответствии с применимым законодательством.' },
          { type: 'h3', text: '1.8 Фотографии, видео и медиаматериалы' },
          { type: 'p', text: 'Проекты Global Fashion Code могут сниматься, фотографироваться и освещаться медиакомандами. Фотографии, видео, интервью и другие проектные материалы могут использоваться для контента сайта, социальных сетей, прессы, портфолио, документирования мероприятий, рекламных материалов, редакционных публикаций, архива и коммуникации с партнёрами. При необходимости использование медиа регулируется отдельным Соглашением о медиарелизе / условиях участия.' },
          { type: 'h3', text: '1.9 Файлы cookie и аналитика' },
          { type: 'p', text: 'Наш сайт может использовать файлы cookie и аналогичные технологии. Строго необходимые cookie используются для функционирования сайта и не могут быть отключены. Необязательные cookie, включая аналитические, маркетинговые, отслеживающие и cookie социальных сетей, используются только там, где это разрешено законом и, при необходимости, только с вашего предварительного согласия. Вы можете принять все cookie, отклонить необязательные или управлять настройками через баннер cookie.' },
          { type: 'h3', text: '1.10 Хранение данных' },
          { type: 'p', text: 'Мы храним персональные данные только столько, сколько необходимо для целей, описанных в настоящей Политике. Данные заявок могут храниться в течение разумного периода для управления отбором, будущими возможностями и коммуникацией с заявителями, если только не запрошено удаление раньше. Фотографии, видео, пресс-материалы, опубликованный контент и проектные архивы могут оставаться доступными там, где они были законно созданы и используются в документальных, редакционных, архивных, портфолийных или рекламных целях.' },
          { type: 'h3', text: '1.11 Ваши права' },
          { type: 'p', text: 'В зависимости от применимого законодательства вы можете иметь право на: запрос доступа к вашим персональным данным; исправление неточных или неполных данных; удаление ваших персональных данных; ограничение обработки; возражение против определённых видов обработки; отзыв согласия в любое время там, где обработка основана на согласии; переносимость данных там, где применимо; подачу жалобы в компетентный орган по защите данных. Для реализации своих прав, пожалуйста, свяжитесь с нами: info@globalfashioncode.com.' },
          { type: 'h3', text: '1.12 Безопасность' },
          { type: 'p', text: 'Мы принимаем разумные технические и организационные меры для защиты персональных данных от несанкционированного доступа, потери, неправомерного использования, изменения или раскрытия.' },
          { type: 'h3', text: '1.13 Изменения в Политике конфиденциальности' },
          { type: 'p', text: 'Мы можем время от времени обновлять настоящую Политику конфиденциальности. Обновлённая версия будет опубликована на этой странице с новой датой последнего обновления.' },
          { type: 'h3', text: '1.14 Контакты' },
          { type: 'p', text: 'По вопросам настоящей Политики конфиденциальности или обработки персональных данных, пожалуйста, обращайтесь: Global Fashion Code / MAG Model Agent Group, info@globalfashioncode.com.' },
        ],
      },
      {
        id: 'cookies',
        nav: 'Политика Cookie',
        title: '2. Политика использования файлов Cookie',
        lastUpdated: 'Последнее обновление: 15.06.2026',
        blocks: [
          { type: 'p', text: 'Настоящая Политика использования файлов cookie объясняет, как Global Fashion Code использует файлы cookie и аналогичные технологии на нашем сайте. Cookie — это небольшие текстовые файлы, сохраняемые на вашем устройстве при посещении сайта. Они помогают сайту работать, запоминать настройки, понимать использование сайта и поддерживать коммуникацию или маркетинговую деятельность.' },
          { type: 'h3', text: '2.1 Типы используемых файлов Cookie' },
          { type: 'p', text: 'Строго необходимые Cookie — обязательны для работы сайта, его безопасности и предоставления основных функций. Их нельзя отключить, так как без них сайт не может нормально функционировать.' },
          { type: 'p', text: 'Аналитические Cookie — помогают нам понять, как посетители используют сайт, какие страницы посещаются и как мы можем улучшить контент, структуру и пользовательский опыт. Используются только с вашего согласия там, где это требуется.' },
          { type: 'p', text: 'Маркетинговые Cookie и Cookie социальных сетей — могут использоваться для измерения кампаний, персонализации контента, взаимодействия с платформами социальных сетей, поддержки рекламной деятельности или оценки эффективности коммуникации. Используются только с вашего согласия там, где это требуется.' },
          { type: 'p', text: 'Функциональные Cookie — могут запоминать ваши настройки, например языковые предпочтения или настройки cookie, где применимо.' },
          { type: 'h3', text: '2.2 Согласие' },
          { type: 'p', text: 'При посещении нашего сайта вы можете принять все cookie, отклонить необязательные или управлять настройками по категориям. Строго необходимые cookie всегда активны, так как они необходимы для работы сайта. Необязательные cookie, включая аналитические, маркетинговые, отслеживающие и cookie социальных сетей, используются только если вы дали согласие там, где это требуется законом. Вы можете изменить или отозвать своё согласие в любое время через ссылку «Настройки Cookie» на сайте.' },
          { type: 'h3', text: '2.3 Cookie третьих сторон' },
          { type: 'p', text: 'Некоторые cookie могут устанавливаться сторонними провайдерами, такими как аналитические инструменты, платформы социальных сетей, провайдеры встроенного контента, рекламные инструменты или платёжные системы. Эти третьи стороны могут обрабатывать данные в соответствии со своими политиками конфиденциальности и использования cookie.' },
        ],
      },
      {
        id: 'terms',
        nav: 'Условия использования',
        title: '3. Условия использования сайта',
        lastUpdated: 'Последнее обновление: 15.06.2026',
        blocks: [
          { type: 'p', text: 'Настоящие Условия использования сайта регулируют использование сайта Global Fashion Code и онлайн-контента. Используя данный сайт, вы соглашаетесь с настоящими Условиями использования.' },
          { type: 'h3', text: '3.1 Оператор сайта' },
          { type: 'meta', label: 'Проект', value: 'Global Fashion Code' },
          { type: 'meta', label: 'Адрес', value: 'Австрия, Куфштайн 6330, Einfangstrasse 6' },
          { type: 'meta', label: 'Email', value: 'info@globalfashioncode.com' },
          { type: 'h3', text: '3.2 Назначение сайта' },
          { type: 'p', text: 'Сайт предоставляет информацию о проектах Global Fashion Code, включая модные мероприятия, кастинги, образовательные программы, показы, конкурсы, возможности для подачи заявок, медиадеятельность и форматы профессионального нетворкинга. Информация на сайте предоставляется в общих информационных и рекламных целях.' },
          { type: 'h3', text: '3.3 Заявки и отбор' },
          { type: 'p', text: 'Подача заявки через сайт не гарантирует принятие, участие, одобрение кастинга, представительство агентством, контракт, награду, публикацию, оплачиваемую работу или какой-либо конкретный профессиональный результат. Global Fashion Code может рассматривать заявки на основе критериев проекта, профессиональной пригодности, доступности, возраста, роста, параметров, портфолио, опыта, потребностей проекта и требований партнёров.' },
          { type: 'h3', text: '3.4 Отсутствие гарантий контрактов или результатов' },
          { type: 'p', text: 'Global Fashion Code создаёт возможности для видимости, обучения, доступа к кастингам, профессионального представления, встреч с агентствами, нетворкинга и медиаприсутствия. Однако окончательные решения относительно контрактов, бронирований, представительства, публикаций, наград, сотрудничества или будущих возможностей принимаются независимыми агентствами, партнёрами, клиентами, СМИ, спонсорами, судьями или профессионалами отрасли. Ни одно утверждение на сайте не должно трактоваться как гарантия контракта, подписания с агентством, оплачиваемой работы, визы, публикации, награды, бронирования или финансового результата.' },
          { type: 'h3', text: '3.5 Интеллектуальная собственность' },
          { type: 'p', text: 'Весь контент сайта, включая названия, логотипы, заголовки проектов, тексты, изображения, видео, графику, макеты, дизайн, концепции, структуры программ и материалы, принадлежит Global Fashion Code или его лицензиарам, если не указано иное. Вы не можете копировать, воспроизводить, распространять, изменять, продавать, публиковать или использовать контент сайта в коммерческих целях без предварительного письменного разрешения.' },
          { type: 'h3', text: '3.6 Поведение пользователей' },
          { type: 'p', text: 'Вы соглашаетесь не злоупотреблять сайтом, не предоставлять ложную информацию, не загружать незаконный контент, не нарушать права третьих сторон, не пытаться получить доступ к ограниченным системам, не наносить вред сайту, не использовать автоматизированные инструменты сбора данных и не совершать действий, которые могут нанести ущерб Global Fashion Code, его партнёрам, участникам или пользователям.' },
          { type: 'h3', text: '3.7 Ограничение ответственности' },
          { type: 'p', text: 'В той мере, в какой это допускается применимым законодательством, Global Fashion Code не несёт ответственности за косвенные убытки, упущенные возможности, отклонённые заявки, технические проблемы, перебои в работе сайта, действия третьих сторон, проблемы с поездками, решения агентств, результаты кастингов или доверие к информации на сайте.' },
          { type: 'h3', text: '3.8 Применимое право' },
          { type: 'p', text: 'Настоящие Условия использования регулируются законодательством Австрии, если только обязательные нормы о защите прав потребителей или иное применимое законодательство не предусматривают иного. Любые споры сначала рассматриваются в доброй воле. Если мирное урегулирование не достигнуто, компетентный суд определяется в соответствии с применимым законодательством.' },
        ],
      },
      {
        id: 'imprint',
        nav: 'Юридическое уведомление',
        title: '4. Юридическое уведомление / Импрессум',
        blocks: [
          { type: 'p', text: 'Информация в соответствии с применимыми австрийскими правовыми требованиями, включая Австрийский закон об электронной коммерции и Закон о СМИ, где применимо.' },
          { type: 'h3', text: 'Оператор сайта / Владелец СМИ' },
          { type: 'meta', label: 'Сайт', value: 'www.globalfashioncode.com' },
          { type: 'meta', label: 'Название', value: 'Global Fashion Code' },
          { type: 'meta', label: 'Юридическое лицо', value: 'MAG Model Agent Group' },
          { type: 'meta', label: 'Адрес', value: 'Einfangstrasse 6, Kufstein 6330, Австрия' },
          { type: 'meta', label: 'Email', value: 'info@globalfashioncode.com' },
          { type: 'h3', text: 'Предмет деятельности' },
          { type: 'p', text: 'Модные мероприятия, модельные кастинги, образовательные программы, модные показы, медиапроекты, профессиональный нетворкинг и смежные услуги.' },
          { type: 'h3', text: 'Отказ от ответственности' },
          { type: 'p', text: 'Мы прилагаем разумные усилия для поддержания точности и актуальности информации на сайте. Однако мы не гарантируем полноту, актуальность или отсутствие ошибок во всей информации.' },
          { type: 'h3', text: 'Внешние ссылки' },
          { type: 'p', text: 'Сайт может содержать ссылки на внешние сайты. Мы не несём ответственности за контент, политику конфиденциальности или безопасность внешних сайтов.' },
          { type: 'h3', text: 'Авторские права' },
          { type: 'p', text: 'Весь контент на данном сайте, включая тексты, изображения, видео, логотипы и элементы дизайна, защищён авторским правом и не может использоваться без предварительного письменного разрешения.' },
        ],
      },
    ],
  },
}
